import NotificationLog from "../models/NotificationLog.js";

const safeLog = async (data) => {
  try {
    await NotificationLog.create(data);
  } catch (err) {
    console.warn("NotificationLog warning (sms):", err.message);
  }
};

/**
 * Universal SMS Dispatcher
 * Dispatches mobile SMS for OTPs, invoice bills, and payment receipts.
 */
export const sendOtpSms = async ({ mobile, otp, businessName = "ABC Traders" }) => {
  const cleanMobile = String(mobile).replace(/\D/g, "");
  const formattedMobile = cleanMobile.startsWith("91") && cleanMobile.length === 12
    ? `+${cleanMobile}`
    : `+91${cleanMobile.slice(-10)}`;

  const text = `[${businessName}] Your security verification OTP is ${otp}. Valid for 5 minutes. Do not share this OTP with anyone.`;

  console.log(`📱 SMS Dispatched to ${formattedMobile}: "${text}"`);

  // Optional: If real SMS API Key (Fast2SMS / Twilio) is configured in process.env.SMS_API_KEY
  if (process.env.SMS_API_KEY) {
    try {
      // Example Fast2SMS or webhook call
      await fetch("https://www.fast2sms.com/dev/bulkV2", {
        method: "POST",
        headers: {
          authorization: process.env.SMS_API_KEY,
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          route: "otp",
          variables_values: otp,
          numbers: cleanMobile.slice(-10)
        })
      });
    } catch (err) {
      console.warn("⚠️ SMS Gateway API warning:", err.message);
    }
  }

  await safeLog({
    type: "sms",
    recipient: formattedMobile,
    title: "OTP Verification SMS",
    message: text,
    status: "delivered",
    meta: { otp, mobile: formattedMobile }
  });

  return {
    success: true,
    recipient: formattedMobile,
    message: text,
    timestamp: new Date().toISOString()
  };
};

export const sendInvoiceSms = async ({ mobile, customerName, invoiceNumber, total, due, businessName = "ABC Traders", currency = "Rs." }) => {
  const cleanMobile = String(mobile).replace(/\D/g, "");
  const formattedMobile = cleanMobile.startsWith("91") && cleanMobile.length === 12
    ? `+${cleanMobile}`
    : `+91${cleanMobile.slice(-10)}`;

  const text = `Dear ${customerName}, invoice #${invoiceNumber} for ${currency} ${Number(total).toFixed(2)} generated by ${businessName}. Balance due: ${currency} ${Number(due).toFixed(2)}. Thank you!`;

  console.log(`📱 Invoice SMS Dispatched to ${formattedMobile}: "${text}"`);

  await safeLog({
    type: "sms",
    recipient: formattedMobile,
    title: `Invoice SMS #${invoiceNumber}`,
    message: text,
    status: "delivered",
    meta: { invoiceNumber, total, due }
  });

  return { success: true, recipient: formattedMobile, message: text };
};

export const sendPaymentSms = async ({ mobile, customerName, invoiceNumber, amount, due, businessName = "ABC Traders", currency = "Rs." }) => {
  const cleanMobile = String(mobile).replace(/\D/g, "");
  const formattedMobile = cleanMobile.startsWith("91") && cleanMobile.length === 12
    ? `+${cleanMobile}`
    : `+91${cleanMobile.slice(-10)}`;

  const text = `Dear ${customerName}, received payment of ${currency} ${Number(amount).toFixed(2)} for invoice #${invoiceNumber}. Remaining balance: ${currency} ${Number(due).toFixed(2)}. - ${businessName}`;

  console.log(`📱 Payment SMS Dispatched to ${formattedMobile}: "${text}"`);

  await safeLog({
    type: "sms",
    recipient: formattedMobile,
    title: `Payment Receipt SMS #${invoiceNumber}`,
    message: text,
    status: "delivered",
    meta: { invoiceNumber, amount, due }
  });

  return { success: true, recipient: formattedMobile, message: text };
};
